config/routes.rb
Rails.application.routes.draw do
  devise_for :technicians
  root 'welcome#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :technician
  belongs_to :client

  validates_presence_of :date, :service
end

app/models/client.rb
class Client < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  has_many :appointments
  has_many :technicians, through: :appointments
  validates_presence_of :name, :phone_number

  def address
    [street, city, state, zipcode].compact.join(', ')
  end
end

app/models/technician.rb
class Technician < ApplicationRecord
  has_many :appointments
  has_many :clients, through: :appointments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
  
  validates_presence_of :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elcamino</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/session_portal' %>
    <%= render 'shared/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if notice %><%= notice %><% end %>
<% if alert %><%= alert %><% end %>

app/views/shared/_session_portal.html.erb
<div class="flex bg-blue-500 text-blue-100">
<% if technician_signed_in? %>
  <span>Welcome, <%= current_technician.first_name %></span>
  <%= link_to "Log out", destroy_technician_session_path, id: 'log-out' %>
<% else %>
  <%= link_to "Login", new_technician_session_path, id: 'login-technician' %>
<% end %>
</div>

app/views/welcome/show.html.erb
<h1>Welcome#show</h1>
<p>Find me in app/views/welcome/show.html.erb</p>